# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "feature/Kelly.Zapata" ]
  pull_request:
    branches: [ "feature/Kelly.Zapata" ]

jobs:
  test:
    permissions: write-all
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
       os: [ubuntu-latest, macOs-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github 
        settings-path: ${{ github.workspace }}
        
    - name: Build with Maven
      if: always()
      run: mvn clean verify
      
    - name: Build with Maven using firefox
      if: always()
      run: mvn clean verify -Ddriver=firefox
      
    - name: Grant execute permissions for gradle
      if: always()
      run: chmod +x gradlew
      
    - name: Build with Gradle
      if: always()
      run: ./gradlew clean test

    - name: Publish Report
      if: always()
      uses: dorny/test-reporter@v1.6.0
      with:
        name: Publish Test Result
        path: "**/target/site/serenity/SERENITY-JUNIT-*.xml"
        reporter: java-junit
        
  AnalizeCode:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github 
        settings-path: ${{ github.workspace}}
       

  
    

